<a href="https://colab.research.google.com/github/shabeeb248/stock-analysis/blob/main/stock_sentiments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install opendatasets --upgrade

In [ ]:
import opendatasets as od
dataset_url = 'https://www.kaggle.com/aaron7sun/stocknews'
od.download(dataset_url)

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: shabeeb248
Your Kaggle Key: ··········


100%|██████████| 5.82M/5.82M [00:00<00:00, 25.4MB/s]

In [ ]:
import pandas as pd
df=pd.read_csv("/content/stocknews/Combined_News_DJIA.csv")
df

Date  ...                                              Top25
0     2008-08-08  ...           b"No Help for Mexico's Kidnapping Surge"
1     2008-08-11  ...  b"So this is what it's come to: trading sex fo...
2     2008-08-12  ...  b"BBC NEWS | Asia-Pacific | Extinction 'by man...
3     2008-08-13  ...  b'2006: Nobel laureate Aleksander Solzhenitsyn...
4     2008-08-14  ...  b'Philippines : Peace Advocate say Muslims nee...
...          ...  ...                                                ...
1984  2016-06-27  ...  Pakistani clerics declare transgender marriage...
1985  2016-06-28  ...  Mexico's security forces routinely use 'sexual...
1986  2016-06-29  ...  Tiny New Zealand town with 'too many jobs' lau...
1987  2016-06-30  ...  Law Enforcement Sources: Gun Used in Paris Ter...
1988  2016-07-01  ...  Ozone layer hole seems to be healing - US &amp...

[1989 rows x 27 columns]

In [ ]:
df.shape

(1989, 27)

In [ ]:
train=df[df["Date"]<"2015-01-01"]
test=df[df["Date"]>"2014-12-31"]


In [ ]:
train

Date  ...                                              Top25
0     2008-08-08  ...           b"No Help for Mexico's Kidnapping Surge"
1     2008-08-11  ...  b"So this is what it's come to: trading sex fo...
2     2008-08-12  ...  b"BBC NEWS | Asia-Pacific | Extinction 'by man...
3     2008-08-13  ...  b'2006: Nobel laureate Aleksander Solzhenitsyn...
4     2008-08-14  ...  b'Philippines : Peace Advocate say Muslims nee...
...          ...  ...                                                ...
1606  2014-12-24  ...  Russia May Be Cut to Junk rating as S&amp;P Sa...
1607  2014-12-26  ...  A leading Russian elected official on Thursday...
1608  2014-12-29  ...      AirAsia Flight's Altitude Request Was Refused
1609  2014-12-30  ...  One of China's most industrialized cities has ...
1610  2014-12-31  ...        At Least 33 Killed in Yemen Suicide Bombing

[1611 rows x 27 columns]

In [ ]:
from dataclasses import replace
#removing puncations

data=train.iloc[:,2:27]
data.replace("[^a-zA-Z]"," ",regex=True,inplace=True)

In [ ]:
data

Top1  ...                                              Top25
0     b Georgia  downs two Russian warplanes  as cou...  ...           b No Help for Mexico s Kidnapping Surge 
1     b Why wont America and Nato help us  If they w...  ...  b So this is what it s come to  trading sex fo...
2     b Remember that adorable   year old who sang a...  ...  b BBC NEWS   Asia Pacific   Extinction  by man...
3     b  U S  refuses Israel weapons to attack Iran ...  ...  b       Nobel laureate Aleksander Solzhenitsyn...
4     b All the experts admit that we should legalis...  ...  b Philippines   Peace Advocate say Muslims nee...
...                                                 ...  ...                                                ...
1606  Death toll among Qatars      World Cup workers...  ...  Russia May Be Cut to Junk rating as S amp P Sa...
1607  Saudis are eagerly awaiting the approval of a ...  ...  A leading Russian elected official on Thursday...
1608  Solar Power Storage Prices Drop     In Germany...  ...      AirAsia Flight s Altitude Request Was Refused
1609  China businessman jailed for    years for buyi...  ...  One of China s most industrialized cities has ...
1610  AirAsia flight found at the bottom of the Java...  ...        At Least    Killed in Yemen Suicide Bombing

[1611 rows x 25 columns]

In [ ]:
#chnge the column name from top1 to 1

list1=[i for i in range(25)]
new_index=[str(i) for i in list1]
data.columns=new_index
data.head(5)

0  ...                                                 24
0  b Georgia  downs two Russian warplanes  as cou...  ...           b No Help for Mexico s Kidnapping Surge 
1  b Why wont America and Nato help us  If they w...  ...  b So this is what it s come to  trading sex fo...
2  b Remember that adorable   year old who sang a...  ...  b BBC NEWS   Asia Pacific   Extinction  by man...
3  b  U S  refuses Israel weapons to attack Iran ...  ...  b       Nobel laureate Aleksander Solzhenitsyn...
4  b All the experts admit that we should legalis...  ...  b Philippines   Peace Advocate say Muslims nee...

[5 rows x 25 columns]

In [ ]:
#converting headings to lower case

for index in new_index:
  data[index]=data[index].str.lower()
data.head(5)

0  ...                                                 24
0  b georgia  downs two russian warplanes  as cou...  ...           b no help for mexico s kidnapping surge 
1  b why wont america and nato help us  if they w...  ...  b so this is what it s come to  trading sex fo...
2  b remember that adorable   year old who sang a...  ...  b bbc news   asia pacific   extinction  by man...
3  b  u s  refuses israel weapons to attack iran ...  ...  b       nobel laureate aleksander solzhenitsyn...
4  b all the experts admit that we should legalis...  ...  b philippines   peace advocate say muslims nee...

[5 rows x 25 columns]

In [ ]:
#combining row in to a paragraph
''.join(str(x) for x in data.iloc[1,0:25])

'b why wont america and nato help us  if they wont help us now  why did we help them in iraq  b bush puts foot down on georgian conflict b jewish georgian minister  thanks to israeli training  we re fending off russia  b georgian army flees in disarray as russians advance   gori abandoned to russia without a shot fired b olympic opening ceremony fireworks  faked  b what were the mossad with fraudulent new zealand passports doing in iraq  b russia angered by israeli military sale to georgia b an american citizen living in s ossetia blames u s  and georgian leaders for the genocide of innocent people b welcome to world war iv  now in high definition  b georgia s move  a mistake of monumental proportions  b russia presses deeper into georgia  u s  says regime change is goal b abhinav bindra wins first ever individual olympic gold medal for india b  u s  ship heads for arctic to define territory b drivers in a jerusalem taxi station threaten to quit rather than work for their new boss   an

In [ ]:
#convert all in to paragraph

headlines=[]
for row in range(0,len(data.index)):
  headlines.append(' '.join(str(x) for x in data.iloc[row,0:25]))
headlines[1]

'b why wont america and nato help us  if they wont help us now  why did we help them in iraq   b bush puts foot down on georgian conflict  b jewish georgian minister  thanks to israeli training  we re fending off russia   b georgian army flees in disarray as russians advance   gori abandoned to russia without a shot fired  b olympic opening ceremony fireworks  faked   b what were the mossad with fraudulent new zealand passports doing in iraq   b russia angered by israeli military sale to georgia  b an american citizen living in s ossetia blames u s  and georgian leaders for the genocide of innocent people  b welcome to world war iv  now in high definition   b georgia s move  a mistake of monumental proportions   b russia presses deeper into georgia  u s  says regime change is goal  b abhinav bindra wins first ever individual olympic gold medal for india  b  u s  ship heads for arctic to define territory  b drivers in a jerusalem taxi station threaten to quit rather than work for their 

In [ ]:
new_strings = []

for string in headlines:
    new_string = string.replace(" b ", " ")
    new_string=new_string[1:]
    new_strings.append(new_string)

new_strings[1]
headlines=new_strings

In [ ]:
headlines[2]

' remember that adorable   year old who sang at the opening ceremonies  that was fake  too   russia  ends georgia operation    if we had no sexual harassment we would have no children      al qa eda is losing support in iraq because of a brutal crackdown on activities it regards as un islamic   including women buying cucumbers  ceasefire in georgia  putin outmaneuvers the west  why microsoft and intel tried to kill the xo      laptop  stratfor  the russo georgian war and the balance of power     i m trying to get a sense of this whole georgia russia war  vote up if you think georgia started it  or down if you think russia did  the us military was surprised by the timing and swiftness of the russian military s move into south ossetia and is still trying to sort out what happened  a us defense official said monday  u s  beats war drum as iran dumps the dollar  gorbachev   georgian military attacked the south ossetian capital of tskhinvali with multiple rocket launchers designed to devast

In [ ]:
df = pd.DataFrame(headlines)

In [ ]:
df

0
0      georgia  downs two russian warplanes  as coun...
1      why wont america and nato help us  if they wo...
2      remember that adorable   year old who sang at...
3       u s  refuses israel weapons to attack iran  ...
4      all the experts admit that we should legalise...
...                                                 ...
1606  eath toll among qatars      world cup workers ...
1607  audis are eagerly awaiting the approval of a n...
1608  olar power storage prices drop     in germany ...
1609  hina businessman jailed for    years for buyin...
1610  irasia flight found at the bottom of the java ...

[1611 rows x 1 columns]

In [ ]:
#download data set

df.to_csv('f.csv',index=False)

In [ ]:
df=headlines

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier

In [ ]:
countvector=CountVectorizer(ngram_range=(2,2))
traindataset=countvector.fit_transform(headlines)

In [ ]:
traindataset

<1611x358203 sparse matrix of type '<class 'numpy.int64'>'
	with 664533 stored elements in Compressed Sparse Row format>

In [ ]:
#impliment randomforest classifier

randomclassifier=RandomForestClassifier(n_estimators=200,criterion="entropy")
randomclassifier.fit(traindataset,train['Label'])


RandomForestClassifier(criterion='entropy', n_estimators=200)

In [ ]:
#prediction for the test data

test_transform= []
for row in range(0,len(test.index)):
   test_transform.append(' '.join(str(x) for x in test.iloc[row,2:27]))

test_dataset=countvector.transform(test_transform)
predictions=randomclassifier.predict(test_dataset)


In [ ]:
predictions

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [ ]:
#import library to check accuracy
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score


In [ ]:
matrix=confusion_matrix(test["Label"],predictions)
print(matrix)
score=accuracy_score(test["Label"],predictions)
print(score)
report=classification_report(test["Label"],predictions)
print(report)

[[  1 185]
 [  1 191]]
0.5079365079365079
              precision    recall  f1-score   support

           0       0.50      0.01      0.01       186
           1       0.51      0.99      0.67       192

    accuracy                           0.51       378
   macro avg       0.50      0.50      0.34       378
weighted avg       0.50      0.51      0.35       378



# using tfid vectorizer

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier

In [ ]:
tfidfvector=TfidfVectorizer(ngram_range=(2,2))
traindataset=tfidfvector.fit_transform(headlines)

In [ ]:
#impliment randomforest classifier

randomclassifier=RandomForestClassifier(n_estimators=200,criterion="entropy")
randomclassifier.fit(traindataset,train['Label'])


RandomForestClassifier(criterion='entropy', n_estimators=200)

In [ ]:
#prediction for the test data

test_transform= []
for row in range(0,len(test.index)):
   test_transform.append(' '.join(str(x) for x in test.iloc[row,2:27]))

test_dataset=tfidfvector.transform(test_transform)
predictions=randomclassifier.predict(test_dataset)

In [ ]:
matrix=confusion_matrix(test["Label"],predictions)
print(matrix)
score=accuracy_score(test["Label"],predictions)
print(score)
report=classification_report(test["Label"],predictions)
print(report)

[[ 58 128]
 [ 48 144]]
0.5343915343915344
              precision    recall  f1-score   support

           0       0.55      0.31      0.40       186
           1       0.53      0.75      0.62       192

    accuracy                           0.53       378
   macro avg       0.54      0.53      0.51       378
weighted avg       0.54      0.53      0.51       378



#multinominal method


In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:

traindataset

<1611x358203 sparse matrix of type '<class 'numpy.float64'>'
	with 664533 stored elements in Compressed Sparse Row format>

In [ ]:
naive=MultinomialNB()
naive.fit(traindataset,train["Label"])

MultinomialNB()

In [ ]:
naive

MultinomialNB()

In [ ]:
#prediction for the test data

test_transform= []
for row in range(0,len(test.index)):
   test_transform.append(' '.join(str(x) for x in test.iloc[row,2:27]))

test_dataset=tfidfvector.transform(test_transform)
predictions=naive.predict(test_dataset)

In [ ]:
matrix=confusion_matrix(test["Label"],predictions)
print(matrix)
score=accuracy_score(test["Label"],predictions)
print(score)
report=classification_report(test["Label"],predictions)
print(report)

[[  0 186]
 [  0 192]]
0.5079365079365079
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       186
           1       0.51      1.00      0.67       192

    accuracy                           0.51       378
   macro avg       0.25      0.50      0.34       378
weighted avg       0.26      0.51      0.34       378



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
